### Obtener una lista de productos que coinciden con la busqueda
GET http://localhost:1234/items?q=smart

### Crear un producto con POST
POST http://localhost:1234/items
Content-Type: application/json

{
  "title":"iPhone X",
  "description":"SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
  "price":899,
  "discountPercentage":17.94,
  "rating":4.44,
  "stock":34,
  "brand":"Apple",
  "category":"smartphones",
  "thumbnail":"https://acdn.mitiendanube.com/stores/001/116/601/products/x-web-black1-c88a6d98d739dd1f8d16376865582511-640-0.jpg",
  "images":[
    "https://i.dummyjson.com/data/products/2/1.jpg",
    "https://i.dummyjson.com/data/products/2/2.jpg",
    "https://i.dummyjson.com/data/products/2/3.jpg",
    "https://i.dummyjson.com/data/products/2/thumbnail.jpg"
  ]
}

### Actualizar un producto
PATCH http://localhost:1234/movies/1
Content-Type: application/json

{
  "stock": 20
}